version: '3.8'

services:
  nest:
    env_file: ./.env

    build:
      context: ./backend
      args:
        workdir: $backend_workdir
    ports:
      - $backend_port:$backend_port
    volumes:
      - ./backend:$backend_workdir
      - $backend_workdir/node_modules

  vue:
    env_file: ./.env

    build:
      context: ./frontend
      args:
        workdir: $frontend_workdir
    ports:
      - $frontend_port:$frontend_port
    volumes:
      - ./frontend:$frontend_workdir
      - $frontend_workdir/node_modules

  nginx:
    depends_on:
      - nest
      - vue
    env_file: ./.env

    image: nginx:1.25.3-alpine
    ports:
      - $nginx_port:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/dist:/var/www/social_wall
      # - $frontend_workdir:/var/www/social_wall
      # - $backend_workdir:/var/www/social_wall
