services:
  vue:
    env_file: ./.env
    

    build:
      context: ./frontend
      target: $frontend_target
      args:
        workdir: $frontend_workdir
    command: npm run dev
    ports:
      - $frontend_port:$frontend_port
    volumes:
      - ./frontend:$frontend_workdir
      - $frontend_workdir/node_modules

  nest:
    env_file: ./.env
    

    build:
      context: ./backend
      target: $backend_target
      args:
        workdir: $backend_workdir
    command: npm run dev
    ports:
      - $backend_port:$backend_port
    volumes:
      - ./backend:$backend_workdir
      - $backend_workdir/node_modules

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./:/var/www
  #     - ./_docker/nginx/conf.d:/etc/nginx/conf.d
  #   ports:
  #     - 8876:80
  #   depends_on:
  #     - app
  #   container_name: shop_nginx

  # app:
  #   build:
  #     context: .
  #     dockerfile: _docker/app/Dockerfile
  #   volumes:
  #     - ./:/var/www
  #   container_name: shop_app
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:8.0
  #   restart: always
  #   volumes:
  #     - ./tmp/db:/var/lib/mysql
  #   environment:
  #       MYSQL_DATABASE: shop
  #       MYSQL_ROOT_PASSWORD: root
  #   ports:
  #     - 8101:3306
  #   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  #   container_name: shop_db
