version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - $bd_port:$bd_port
    environment:
      - MONGODB_DATABASE="test"

  nestjs:
    depends_on:
      - mongodb
    env_file: ./.env

    build:
      context: ./api
      args:
        workdir: $api_workdir
    ports:
      - $api_port:$api_port
    volumes:
      - ./api:$api_workdir
      - v_nestjs:$api_workdir/node_modules

  vuejs:
    env_file: ./.env

    build:
      context: ./client
      args:
        workdir: $client_workdir
    ports:
      - $client_port:$client_port
    volumes:
      - ./client:$client_workdir
      - v_vuejs:$client_workdir/node_modules

  nginx:
    depends_on:
      - nestjs
      - vuejs
    env_file: ./.env

    image: nginx:1.25.3-alpine
    restart: always
    ports:
      - $web_port:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  v_nestjs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./api/node_modules

  v_vuejs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./client/node_modules
