version: '3.8'

services:
  nest:
    env_file: ./.env

    build:
      context: ./backend
      target: $backend_target
      args:
        workdir: $backend_workdir
    command: npm run dev
    ports:
      - $backend_port:$backend_port
    volumes:
      - ./backend:$backend_workdir
      - $backend_workdir/node_modules

  vue:
    env_file: ./.env

    build:
      context: ./frontend
      target: $frontend_target
      args:
        workdir: $frontend_workdir
    command: npm run dev
    ports:
      - $frontend_port:$frontend_port
    volumes:
      - ./frontend:$frontend_workdir
      - $frontend_workdir/node_modules

  nginx:
    depends_on:
      - nest
      - vue

    image: nginx:1.25.3-alpine
    ports:
      - '8000:80'
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
