version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - $bd_port:$bd_port
    environment:
      - MONGODB_DATABASE="test"

  nestjs:
    depends_on:
      - mongodb
    env_file: ./.env

    build:
      context: ./api
      args:
        workdir: $api_workdir
    ports:
      - $api_port:$api_port

  vuejs:
    env_file: ./.env

    build:
      context: ./client
      args:
        workdir: $client_workdir
    ports:
      - $client_port:$client_port

  nginx:
    depends_on:
      - nestjs
      - vuejs
    env_file: ./.env

    image: nginx:1.25.3-alpine
    restart: always
    ports:
      - $web_port:80
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
