export { default as app_body } from './app_body.vue'
export { default as app_footer } from './app_footer.vue'
export { default as app_header } from './app_header.vue'
export { default as app_record } from './app_record.vue'
export { default as choise_user } from './choise_user.vue'
export { default as the_news } from './the_news.vue'
export { default as app_wrapper } from './app_wrapper.vue'
